package com.zyb.ssm.mapper;

import com.zyb.ssm.pojo.Department;
import com.zyb.ssm.pojo.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    Department selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_dept
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByPrimaryKey(Department record);
}