package com.zyb.ssm.mapper;

import com.zyb.ssm.pojo.Employee;
import com.zyb.ssm.pojo.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);
    List<Employee> selectWithDept();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    Employee selectByPrimaryKey(Integer empId);
    Employee selectByPrimaryKeyWithDept(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_emp
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    int updateByPrimaryKey(Employee record);
}