package com.zyb.ssm.pojo;

import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_dept.dept_id
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_dept.dept_name
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    private String deptName;

    public Department() {
    }

    public Department(Integer deptId, String deptName) {
        this.deptId = deptId;
        this.deptName = deptName;
    }

    @Override
    public String toString() {
        return "Department{" +
                "deptId=" + deptId +
                ", deptName='" + deptName + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_dept.dept_id
     *
     * @return the value of tb1_dept.dept_id
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_dept.dept_id
     *
     * @param deptId the value for tb1_dept.dept_id
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_dept.dept_name
     *
     * @return the value of tb1_dept.dept_name
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_dept.dept_name
     *
     * @param deptName the value for tb1_dept.dept_name
     *
     * @mbggenerated Fri Aug 12 10:26:32 CST 2022
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}